Repository Uspacy/activities-widget, pull requests merged in 2025-03, with the labels that each got.

#9 [799] Style activity widget
  src/components/ActivitiesWidget/index.tsx
  src/components/ActivitiesWidget/types.ts
  src/components/ActivitiesWidget/ui/primitives.tsx
  src/locales/en-US/translation.json
  src/locales/es-ES/translation.json
  src/locales/pl/translation.json
  src/locales/pt-BR/translation.json
  src/locales/uk/translation.json
  src/static/images/calendar-check.svg
  src/static/images/chat-messages.svg
  src/static/images/empty-activity.svg
  src/static/images/google-meet.svg
  src/static/images/mail.svg
  src/static/images/microsoft-teams.svg
  src/static/images/phone.svg
  src/static/images/users.svg
  src/static/images/zoom.svg
Labels: size/xl

#10 Update package.json
  package.json
  yarn.lock
Labels: size/m

#11 [799] Set color for empty activity icon
  src/components/ActivitiesWidget/index.tsx
Labels: size/xs

#12 [799] Comment out AddButton for future implementation
  src/components/ActivitiesWidget/index.tsx
Labels: size/s, size/xs

#13 [feat] update pl locize
  src/locales-widget/pl/translation.json
Labels: size/s
